import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthHeader from "@/components/layouts/AuthHeader";
import Header from "@/components/layouts/Header";
import "./globals.css";
import { ThemeProvider } from "@/src/theme/ThemeProvider";
import { AuthProvider } from "@/src/auth/AuthContext";
import { ProtectedRoute } from '@/src/auth/ProtectedRoute';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
            {/* <ProtectedRoute> */}
              <AuthHeader>
                {children}
              </AuthHeader>
            {/* </ProtectedRoute> */}
        </ThemeProvider>
          </AuthProvider>
      </body>
    </html>
  );
}
